name: env_ld_bp
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - openssl=3.0.7
  - pip=22.3.1
  - python=3.9.15
  - setuptools=65.6.3
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
      - alembic==1.9.1
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - attrs==22.2.0
      - azure-core==1.26.1
      - azure-storage-blob==12.14.1
      - beautifulsoup4==4.11.1
      - binaryornot==0.4.4
      - black==22.12.0
      - bleach==5.0.1
      - bokeh==3.0.3
      - certifi==2022.12.7
      - cffi==1.15.1
      - cfgv==3.3.1
      - chardet==5.1.0
      - charset-normalizer==2.1.1
      - click==8.1.3
      - cloudpickle==2.2.0
      - clumper==0.2.15
      - commonmark==0.9.1
      - contourpy==1.0.6
      - cookiecutter==2.1.1
      - cryptography==39.0.0
      - cycler==0.11.0
      - databricks-cli==0.17.4
      - defusedxml==0.7.1
      - distlib==0.3.6
      - docker==6.0.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.1.0
      - fastjsonschema==2.16.2
      - filelock==3.9.0
      - flake8==6.0.0
      - flask==2.2.2
      - fonttools==4.38.0
      - fqdn==1.5.1
      - gitdb==4.0.10
      - gitpython==3.1.30
      - greenlet==2.0.1
      - htmlmin==0.1.12
      - human-learn==0.3.1
      - identify==2.5.12
      - idna==3.4
      - imagehash==4.3.1
      - importlib-metadata==5.2.0
      - iniconfig==1.1.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isodate==0.6.1
      - isoduration==20.11.0
      - isort==5.11.4
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - jinja2-time==0.2.0
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-console==6.4.4
      - jupyter-core==5.1.1
      - jupyter-events==0.5.0
      - jupyter-server==2.0.6
      - jupyter-server-terminals==0.4.3
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - llvmlite==0.39.1
      - mako==1.2.4
      - markdown==3.4.1
      - markupsafe==2.1.1
      - matplotlib==3.6.2
      - mccabe==0.7.0
      - mistune==2.0.4
      - mlflow==2.1.1
      - msrest==0.7.1
      - multimethod==1.9.1
      - mypy==0.991
      - mypy-extensions==0.4.3
      - nbclassic==0.4.8
      - nbclient==0.7.2
      - nbconvert==7.2.7
      - nbformat==5.7.1
      - networkx==2.8.8
      - nodeenv==1.7.0
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - numba==0.56.4
      - numpy==1.23.5
      - oauthlib==3.2.2
      - openpyxl==3.0.10
      - pandas==1.5.2
      - pandas-profiling==3.6.2
      - pandocfilters==1.5.0
      - pathspec==0.10.3
      - patsy==0.5.3
      - phik==0.12.3
      - pillow==9.4.0
      - plotly==5.11.0
      - plotly-express==0.4.1
      - pluggy==1.0.0
      - pre-commit==2.21.0
      - prometheus-client==0.15.0
      - protobuf==4.21.12
      - pyarrow==10.0.1
      - pycodestyle==2.10.0
      - pycparser==2.21
      - pydantic==1.10.4
      - pyflakes==3.0.1
      - pyjwt==2.6.0
      - pyrsistent==0.19.3
      - pytest==7.2.0
      - python-json-logger==2.0.4
      - python-slugify==7.0.0
      - pytz==2022.7
      - pywavelets==1.4.1
      - pyyaml==6.0
      - qtconsole==5.4.0
      - qtpy==2.3.0
      - querystring-parser==1.2.4
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.0.0
      - scikit-learn==1.2.0
      - scipy==1.9.3
      - seaborn==0.12.2
      - send2trash==1.8.0
      - shap==0.41.0
      - shapely==2.0.0
      - slicer==0.0.7
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.3.2.post1
      - sqlalchemy==1.4.46
      - sqlparse==0.4.3
      - statsmodels==0.13.5
      - tabulate==0.9.0
      - tangled-up-in-unicode==0.2.0
      - tenacity==8.1.0
      - terminado==0.17.1
      - text-unidecode==1.3
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tqdm==4.64.1
      - traitlets==5.8.0
      - typeguard==2.13.3
      - typing-extensions==4.4.0
      - uri-template==1.2.0
      - urllib3==1.26.13
      - virtualenv==20.17.1
      - visions==0.7.5
      - waitress==2.1.2
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.4.2
      - werkzeug==2.2.2
      - widgetsnbextension==4.0.5
      - xyzservices==2022.9.0
      - zipp==3.11.0
